function createAllItems() {
    items.push(new Item({itemName:"Basic Dropper",multiplier:2,tier:"Ascension",rarity:12,usage:"dropper",itemSpeed:1000}));
    items.push(new Item({itemName:"Candy Materializer",multiplier:25,tier:"Ascension",rarity:1,usage:"dropper",itemSpeed:1250}));
    items.push(new Item({itemName:"Antimatter Drill",multiplier:150,tier:"Revival",rarity:1,usage:"dropper",itemSpeed:500}));
    items.push(new Item({itemName:"Mars Drill",multiplier:500,tier:"Supernatural",rarity:0.5,usage:"dropper",itemSpeed:750}));
    items.push(new Item({itemName:"Neptunium Excavator",multiplier:7500,tier:"Supernatural",rarity:0.1,usage:"dropper",itemSpeed:750}));
    items.push(new Item({itemName:"Planetary Annihilator",multiplier:100000,tier:"Conglomerate",rarity:"???",usage:"dropper",itemSpeed:2000}));
    items.push(new Item({itemName:"Solar Decimator",multiplier:1000000,tier:"Renewal",rarity:1,usage:"dropper",itemSpeed:400}));
    items.push(new EffectGiver({itemName:"Galaxy Crusher",multiplier:100000000,effect:"cosmos",tier:"Awakened",rarity:1,usage:"dropper",itemSpeed:200}));
    items.push(new EffectGiver({itemName:"Supercluster Dissolver",multiplier:1000000000000,effect:"cosmos",tier:"Abyssal",rarity:"???",usage:"dropper",itemSpeed:100}));
    items.push(new EffectGiver({itemName:"Universe Creator",multiplier:1000000000000000000,effect:"cosmos",tier:"Abyssal",rarity:"???",usage:"dropper",itemSpeed:50}));
    items.push(new Item({itemName:"Kirbnite Quarry",multiplier:1e+21,tier:"Indescribable",rarity:0.000001,usage:"dropper",itemSpeed:75}));
    items.push(new Item({itemName:"Basic Processor",multiplier:2,tier:"Ascension",rarity:12,usage:"processor",itemSpeed:0}));
    items.push(new Item({itemName:"Laser-Powered Garbage Can",multiplier:20,tier:"Ascension",rarity:1,usage:"processor",itemSpeed:0}));
    items.push(new Item({itemName:"Incineration Plant",multiplier:250,tier:"Revival",rarity:1,usage:"processor",itemSpeed:0}));
    items.push(new Item({itemName:"Wormhole",multiplier:1000,tier:"Supernatural",rarity:0.1,usage:"processor",itemSpeed:0}));
    items.push(new Item({itemName:"Timeline Shredder",multiplier:25000,tier:"Conglomerate",rarity:"???",usage:"processor",itemSpeed:0}));
    items.push(new EffectGiver({itemName:"Black Hole Consumer",multiplier:1500000,effect:"cosmos",tier:"Renewal",rarity:1,usage:"processor",itemSpeed:0}));
    items.push(new EffectGiver({itemName:"Center of the Galaxy",multiplier:50000000,effect:"cosmos",tier:"Awakened",rarity:1,usage:"processor",itemSpeed:0}));
    items.push(new EffectGiver({itemName:"Supernova Condenser",multiplier:1000000000,effect:"cosmos",tier:"Abyssal",rarity:"???",usage:"processor",itemSpeed:0}));
    items.push(new Item({itemName:"The End of Days",multiplier:100000000000,tier:"Indescribable",rarity:0.000001,usage:"processor",itemSpeed:0}));
    items.push(new Item({itemName:"Basic Upgrader",multiplier:1.1,tier:"Ascension",rarity:12,usage:"upgrader",itemSpeed:300}));
    items.push(new Buffgrader({itemName:"Antibody Synthesizer",multiplier:1.4,buffs:"poison",tier:"Ascension",rarity:8,usage:"upgrader",itemSpeed:800}));
    items.push(new Item({itemName:"Uninteresting Refinery",multiplier:1.1,tier:"Ascension",rarity:12,usage:"upgrader",itemSpeed:250}));
    items.push(new EffectGiver({itemName:"Poison Dart Frog Injector",multiplier:1.15,effect:"poison",tier:"Ascension",rarity:11,usage:"upgrader",itemSpeed:250}));
    items.push(new EffectGiver({itemName:"Un-Frozen Pond",multiplier:1.5,effect:"frozen",tier:"Ascension",rarity:8,usage:"upgrader",itemSpeed:200}));
    items.push(new EffectGiver({itemName:"Elsa",multiplier:3,effect:"frozen",tier:"Ascension",rarity:1,usage:"upgrader",itemSpeed:0}));
    items.push(new Buffgrader({itemName:"Homemade Popsicle",multiplier:5.5,buffs:"frozen",tier:"Supernatural",rarity:0.75,usage:"upgrader",itemSpeed:500}));
    items.push(new EffectGiver({itemName:"Wasp Stingifier",multiplier:2,effect:"poison",tier:"Ascension",rarity:2,usage:"upgrader",itemSpeed:0}));
    items.push(new EffectGiver({itemName:"Thriving Forest",multiplier:2.5,effect:"fire",tier:"Ascension",rarity:2,usage:"upgrader",itemSpeed:600}));
    items.push(new EffectGiver({itemName:"Super-Duper-Long-Range-Freeze-Blaster",multiplier:50,effect:"frozen",tier:"Supernatural",rarity:0.1,usage:"upgrader",itemSpeed:0}));
    items.push(new EffectGiver({itemName:"Fusion Reactor",multiplier:50,effect:"fire",tier:"Revival",rarity:3,usage:"upgrader",itemSpeed:350}));
    items.push(new Item({itemName:"Godlike Annihalator",multiplier:45,tier:"Revival",rarity:3,usage:"upgrader",itemSpeed:190}));
    items.push(new Buffgrader({itemName:"The Power of The Sun",multiplier:30,buffs:"fire",tier:"Revival",rarity:2,usage:"upgrader",itemSpeed:250}));
    items.push(new Item({itemName:"Moonlit Waterfall",multiplier:1.75,tier:"Ascension",rarity:3,usage:"upgrader",itemSpeed:220}));
    items.push(new EffectGiver({itemName:"Flames of Redemption",multiplier:3.25,effect:"fire",tier:"Ascension",rarity:1,usage:"upgrader",itemSpeed:0}));
    items.push(new Item({itemName:"Warp Drive",multiplier:2000,tier:"Revival",rarity:3,usage:"upgrader",itemSpeed:400}));
    items.push(new EffectGiver({itemName:"Laser Amplifier",multiplier:1.45,effect:"fire",tier:"Ascension",rarity:3,usage:"upgrader",itemSpeed:0}));
    items.push(new EffectGiver({itemName:"Natural Refiner",multiplier:1.25,effect:"fire",tier:"Ascension",rarity:6,usage:"upgrader",itemSpeed:350}));
    items.push(new Item({itemName:"Sand Blaster",multiplier:1.3,tier:"Ascension",rarity:7,usage:"upgrader",itemSpeed:450}));
    items.push(new EffectGiver({itemName:"Igloo Enhancer",multiplier:1.2,effect:"frozen",tier:"Ascension",rarity:10,usage:"upgrader",itemSpeed:550}));
    items.push(new Item({itemName:"Ore Ruster",multiplier:1.21,tier:"Ascension",rarity:10,usage:"upgrader",itemSpeed:650}));
    items.push(new EffectGiver({itemName:"Cryptocurrency Enchanter",multiplier:1.6,effect:"fraud",tier:"Ascension",rarity:5,usage:"upgrader",itemSpeed:500}));
    items.push(new Buffgrader({itemName:"True Darkness",multiplier:100,buffs:"void",tier:"Revival",rarity:1,usage:"upgrader",itemSpeed:200}));
    items.push(new EffectGiver({itemName:"Containment Breach",multiplier:1.2,effect:"poison",tier:"Ascension",rarity:10,usage:"upgrader",itemSpeed:400}));
    items.push(new Buffgrader({itemName:"Laundered Refiner",multiplier:25000,buffs:"fraud",tier:"Renewal",rarity:1,usage:"upgrader",itemSpeed:300}));
    items.push(new Item({itemName:"Apple Pieifier",multiplier:1.11,tier:"Ascension",rarity:12,usage:"upgrader",itemSpeed:400}));
    items.push(new EffectGiver({itemName:"Toxic Waste Disposal",multiplier:1.25,effect:"poison",tier:"Ascension",rarity:8,usage:"upgrader",itemSpeed:350}));
    items.push(new Item({itemName:"Golden Assembler",multiplier:1.95,tier:"Ascension",rarity:2,usage:"upgrader",itemSpeed:325}));
    items.push(new EffectGiver({itemName:"Voided Corruptor",multiplier:25,effect:"void",tier:"Supernatural",rarity:0.5,usage:"upgrader",itemSpeed:200}));
    items.push(new Item({itemName:"Diamond Edged Blade",multiplier:15,tier:"Supernatural",rarity:0.75,usage:"upgrader",itemSpeed:0}));
    items.push(new Item({itemName:"Pyrmidal Complex",multiplier:40,tier:"Supernatural",rarity:0.4,usage:"upgrader",itemSpeed:180}));
    items.push(new EffectGiver({itemName:"OLAF",multiplier:10,effect:"frozen",tier:"Conglomerate",rarity:"???",usage:"upgrader",itemSpeed:0}));
    items.push(new EffectGiver({itemName:"Wasp Mutator",multiplier:5,effect:"poison",tier:"Conglomerate",rarity:"???",usage:"upgrader",itemSpeed:0}));
    items.push(new EffectGiver({itemName:"The Blockchain",multiplier:7.5,effect:"fraud",tier:"Conglomerate",rarity:"???",usage:"upgrader",itemSpeed:200}));
    items.push(new Item({itemName:"Sharpness III Diamond Sword",multiplier:250,tier:"Conglomerate",rarity:"???",usage:"upgrader",itemSpeed:0}));
    items.push(new EffectGiver({itemName:"Interdimensional Explorer",multiplier:10000,effect:"cosmos",tier:"Renewal",rarity:2,usage:"upgrader",itemSpeed:250}));
    items.push(new Item({itemName:"Diamondal Complex",multiplier:500,tier:"Conglomerate",rarity:"???",usage:"upgrader",itemSpeed:300}));
    items.push(new Buffgrader({itemName:"National Park Refiner",multiplier:50,buffs:"nature",tier:"Conglomerate",rarity:"???",usage:"upgrader",itemSpeed:375}));
    items.push(new EffectGiver({itemName:"Ultimate Deluxe Laser Pointer",multiplier:40,effect:"fire",tier:"Conglomerate",rarity:"???",usage:"upgrader",itemSpeed:0}));
    items.push(new EffectGiver({itemName:"Antarctic Transporter",multiplier:250,effect:"frozen",tier:"Conglomerate",rarity:"???",usage:"upgrader",itemSpeed:275}));
    items.push(new Buffgrader({itemName:"Popsicle Empire",multiplier:75,buffs:"frozen",tier:"Conglomerate",rarity:"???",usage:"upgrader",itemSpeed:200}));
    items.push(new EffectGiver({itemName:"Nuclear Fission Reactor",multiplier:200,effect:"fire",tier:"Conglomerate",rarity:"???",usage:"upgrader",itemSpeed:250}));
    items.push(new EffectGiver({itemName:"No Longer A Thriving Forest Refiner",multiplier:25,effect:"fire",tier:"Conglomerate",rarity:"???",usage:"upgrader",itemSpeed:175}));
    items.push(new Item({itemName:"Moonlit Cashflow",multiplier:60,tier:"Supernatural",rarity:0.2,usage:"upgrader",itemSpeed:160}));
    items.push(new EffectGiver({itemName:"Galactic Nebulator",multiplier:12500,effect:"cosmos",tier:"Renewal",rarity:2,usage:"upgrader",itemSpeed:0}));
    items.push(new Item({itemName:"Spectacular Amalgamation",multiplier:1000000000,tier:"Indescribable",rarity:0.000001,usage:"upgrader",itemSpeed:5}));
    items.push(new Item({itemName:"Wooden Corroder",multiplier:1.05,tier:"Ascension",rarity:12,usage:"upgrader",itemSpeed:175}));
    items.push(new Buffgrader({itemName:"Serenity",multiplier:1000000000,buffs:"spectrum",tier:"Indescribable",rarity:0.000001,usage:"upgrader",itemSpeed:7.5}));
    items.push(new Item({itemName:"Eyeglass Dissolver",multiplier:1.8,tier:"Ascension",rarity:3,usage:"upgrader",itemSpeed:150}));
    items.push(new Item({itemName:"Incarnation Stresser",multiplier:1.4,tier:"Ascension",rarity:6,usage:"upgrader",itemSpeed:150}));
    items.push(new Item({itemName:"Gersh Device",multiplier:1.33,tier:"Ascension",rarity:7,usage:"upgrader",itemSpeed:200}));
    items.push(new Item({itemName:"Three Sided Dice",multiplier:1.38,tier:"Ascension",rarity:7,usage:"upgrader",itemSpeed:200}));
    items.push(new Item({itemName:"Rage Inducer",multiplier:1,tier:"Ascension",rarity:0.000001,usage:"upgrader",itemSpeed:9999}));
    items.push(new EffectGiver({itemName:"Gamma Ray Refiner",multiplier:7500,effect:"cosmos",tier:"Renewal",rarity:2,usage:"upgrader",itemSpeed:0}));
    items.push(new Item({itemName:"Optic Chiasma",multiplier:4,tier:"Ascension",rarity:1,usage:"upgrader",itemSpeed:225}));
    items.push(new EffectGiver({itemName:"Ore Abstractor",multiplier:1.12,effect:"spectrum",tier:"Ascension",rarity:11,usage:"upgrader",itemSpeed:300}));
    items.push(new Item({itemName:"U.I. Vaporizer",multiplier:1.55,tier:"Ascension",rarity:5,usage:"upgrader",itemSpeed:250}));
    items.push(new EffectGiver({itemName:"Mirage Flower",multiplier:1.4,effect:"nature",tier:"Ascension",rarity:6,usage:"upgrader",itemSpeed:220}));
    items.push(new EffectGiver({itemName:"Spider Rain",multiplier:1.45,effect:"poison",tier:"Ascension",rarity:5,usage:"upgrader",itemSpeed:0}));
    items.push(new EffectGiver({itemName:"Fading Rainbow",multiplier:1.3,effect:"void",tier:"Ascension",rarity:8,usage:"upgrader",itemSpeed:280}));
    items.push(new Item({itemName:"Vehicular Manslaughter",multiplier:25.6,tier:"Supernatural",rarity:0.4,usage:"upgrader",itemSpeed:120}));
    items.push(new Item({itemName:"Omnipotence",multiplier:3000,tier:"Renewal",rarity:3,usage:"upgrader",itemSpeed:160}));
    items.push(new EffectGiver({itemName:"Shadow Dodger",multiplier:1.25,effect:"void",tier:"Ascension",rarity:7,usage:"upgrader",itemSpeed:200}));
    items.push(new Buffgrader({itemName:"Reapers Scythe",multiplier:75,buffs:"eerie",tier:"Supernatural",rarity:0.15,usage:"upgrader",itemSpeed:90}));
    items.push(new Buffgrader({itemName:"Reapers Vengeance",multiplier:75,buffs:"eerie",tier:"Supernatural",rarity:0.15,usage:"upgrader",itemSpeed:80}));
    items.push(new Item({itemName:"Ultima Hypocrita",multiplier:1.23,tier:"Ascension",rarity:9,usage:"upgrader",itemSpeed:160}));
    items.push(new EffectGiver({itemName:"Bnuuygirl Bnuuyifier",multiplier:1000000000000,effect:"nature",tier:"Indescribable",rarity:1e-7,usage:"upgrader",itemSpeed:5}));
    items.push(new EffectGiver({itemName:"Catgirl Catgirlifier",multiplier:1000000000000,effect:"nature",tier:"Indescribable",rarity:1e-7,usage:"upgrader",itemSpeed:5}));
    items.push(new Item({itemName:"Sacrificial Armageddon",multiplier:25000000,tier:"Awakened",rarity:3,usage:"upgrader",itemSpeed:50}));
    items.push(new Buffgrader({itemName:"Cosmic Destructor",multiplier:7500000000,buffs:"destruction",tier:"Awakened",rarity:1,usage:"upgrader",itemSpeed:0}));
    items.push(new EffectGiver({itemName:"Otherworldly Creature",multiplier:90000000,effect:"eerie",tier:"Awakened",rarity:2,usage:"upgrader",itemSpeed:35}));
    items.push(new Buffgrader({itemName:"Gravitational Combiner",multiplier:500000000,buffs:"cosmos",tier:"Awakened",rarity:1,usage:"upgrader",itemSpeed:40}));
    items.push(new EffectGiver({itemName:"Apocalyptic Collider",multiplier:10000000,effect:"destruction",tier:"Abyssal",rarity:"???",usage:"upgrader",itemSpeed:20}));
    items.push(new EffectGiver({itemName:"All Seeing Eye",multiplier:7500000,effect:"eerie",tier:"Abyssal",rarity:"???",usage:"upgrader",itemSpeed:15}));
    items.push(new EffectGiver({itemName:"Solar System Combustor",multiplier:50000000,effect:"destruction",tier:"Abyssal",rarity:"???",usage:"upgrader",itemSpeed:15}));
    items.push(new EffectGiver({itemName:"Cult Manipulator",multiplier:90000000,effect:"eerie",tier:"Awakened",rarity:2,usage:"upgrader",itemSpeed:40}));
    items.push(new EffectGiver({itemName:"Big Brother",multiplier:80500000,effect:"eerie",tier:"Awakened",rarity:2,usage:"upgrader",itemSpeed:30}));
    items.push(new EffectGiver({itemName:"Literally 1984",multiplier:75000000,effect:"eerie",tier:"Awakened",rarity:2,usage:"upgrader",itemSpeed:35}));
    items.push(new EffectGiver({itemName:"Disturbance Inducer",multiplier:100000000,effect:"eerie",tier:"Awakened",rarity:1,usage:"upgrader",itemSpeed:30}));
    items.push(new Item({itemName:"The Hypothalamus",multiplier:1000000,tier:"Indescribable",rarity:0.0001,usage:"upgrader",itemSpeed:15}));
    items.push(new Item({itemName:"Stained Reverance",multiplier:1000000,tier:"Indescribable",rarity:0.0001,usage:"upgrader",itemSpeed:15}));
    items.push(new Item({itemName:"Oceans Treasure",multiplier:1.45,tier:"Ascension",rarity:4,usage:"upgrader",itemSpeed:220}));
    items.push(new Item({itemName:"Quartz Enricher",multiplier:1.5,tier:"Ascension",rarity:4,usage:"upgrader",itemSpeed:300}));
    items.push(new Buffgrader({itemName:"Bomb Factory",multiplier:100,buffs:"destruction",tier:"Supernatural",rarity:0.1,usage:"upgrader",itemSpeed:200}));
    items.push(new EffectGiver({itemName:"Eternal Damnation",multiplier:667000000,effect:"eerie",tier:"Awakened",rarity:1,usage:"upgrader",itemSpeed:40}));
}
